apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tsap
  description: Sample service with CI/CD
  annotations:
    github.com/project-slug: devops-champ/tsap
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: devops-champ_tsap
    roadie-backstage-pull-requests/default-filter: "is:open is:pr"
    platform.io/argocd-dev: guestbook-dev
    platform.io/argocd-qa: guestbook-qa
    platform.io/argocd-prod: guestbook-prod
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  dependsOn:
    - resource:default/orders-db
    - resource:default/kafka-cluster
